resilience4j:
  retry:
    instances:
      getByUserId:
        maxRetryAttemps: 5
        waitDuration: 1s

      getById:
        maxRetryAttemps: 5
        waitDuration: 1s

      getAllNote:
        maxRetryAttemps: 5
        waitDuration: 1s

  ratelimiter:
    instances:
      getByUserId:
        limitForPeriod: 1
        limitRefreshPeriod: 3s
        timeoutDuration: 2s
      getById:
        limitForPeriod: 1
        limitRefreshPeriod: 3s
        timeoutDuration: 2s
      addNote:
        limitForPeriod: 1
        limitRefreshPeriod: 2s
        timeoutDuration: 3s
      getAll:
        limitForPeriod: 1
        limitRefreshPeriod: 3s
        timeoutDuration: 3s

spring:
  application:
    name: NOTE-SERVICE



#eureka:
#  client:
#    register-with-eureka:
#      value: true
#    fetch-registry:
#      value: true;
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#    instance:
#      hostname: localhost

  config:
    import: "optional:configserver:"
  cloud:
    config:
      name: config-server
      uri: http://localhost:8888
